/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.assets;

import javax.swing.ImageIcon;

/**
 *
 * @author Kirin
 */
public class CategoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form CategoryPanel
     */
    public CategoryPanel() {
        initComponents();
        setCategoryPanelSize();
        
    }

    public void setCategoryImage(String imagePath) {
        // Load the image from the specified path
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        
        // Set the image for the PictureBox
        PictureBox.setIcon(icon);
    }
    
    public void setCategoryName(String categoryName) {
        CategoryName.setText(categoryName);
    }
    
    private void setCategoryPanelSize() {
        setPreferredSize(new java.awt.Dimension(220, 320));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PictureBox = new javax.swing.JLabel();
        CategoryName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 211, 199));

        PictureBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/images/seafood.jpg"))); // NOI18N
        PictureBox.setPreferredSize(new java.awt.Dimension(220, 320));

        CategoryName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CategoryName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CategoryName.setText("CATEGORY NAME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PictureBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CategoryName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PictureBox, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CategoryName)
                .addGap(0, 50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryName;
    private javax.swing.JLabel PictureBox;
    // End of variables declaration//GEN-END:variables
}
