/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.assets;

import com.app.details.FoodItem;
import com.app.details.FoodStorage;
import com.app.transaction.CartSection;
import com.app.transaction.OrderPanelListener;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Kirin
 */
public class OrderPanel extends javax.swing.JPanel {

    private String orderId;  // Declare the orderId field

    ImageIcon originalIcon;
    ImageIcon scaledIcon;

    private OrderPanelListener orderPanelListener;
    private CartSection cartSection;  // Reference to the CartSection
    private int quantity;
    
    
    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() {
        initComponents();
        
    }
    
    public JButton getCartButton() {
    return CartButton;
}

    /**
     * Set the listener for the OrderPanel.
     * 
     * @param listener The listener to set.
     */
    public void setOrderPanelListener(OrderPanelListener listener) {
        this.orderPanelListener = listener;
    }

    /**
     * Set the CartSection for this OrderPanel.
     * 
     * @param cartSection The CartSection to set.
     */
    public void setCartSection(CartSection cartSection) {
        this.cartSection = cartSection;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
        Quantity.setText(String.valueOf(quantity));
    }

    public int getQuantity() {
        return Integer.parseInt(Quantity.getText());
    }
    
    // Add this method to set the order ID
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
   
    public void setOrderImage(ImageIcon imageIcon) {
        // Set the image for the PictureBox
        OrderImage.setIcon(imageIcon);
    }
    
    public void setFoodName(String foodName) {
        FoodName.setText(foodName);
    }
    
    public void setFoodDescription(String foodDescription) {
        FoodDescription.setText(foodDescription);
    }
    
    public void setFoodPrice(double foodPrice) {
        // Convert the double value to a formatted string if needed
        String formattedPrice = String.format("%.2f", foodPrice);
        FoodPrice.setText(formattedPrice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderPanelBG = new javax.swing.JPanel();
        OrderImage = new javax.swing.JLabel();
        OrderPanel = new javax.swing.JPanel();
        FoodPrice = new javax.swing.JLabel();
        QuantityLabel = new javax.swing.JLabel();
        FoodName = new javax.swing.JLabel();
        FoodDescription = new javax.swing.JLabel();
        MinusButton = new com.app.assets.ColoredButton();
        plusButton = new com.app.assets.ColoredButton();
        Quantity = new javax.swing.JLabel();
        CartButton = new com.app.assets.ColoredButton();

        setPreferredSize(new java.awt.Dimension(410, 280));
        setRequestFocusEnabled(false);

        OrderPanelBG.setBackground(new java.awt.Color(145, 196, 131));
        OrderPanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/images/foodimage.png"))); // NOI18N
        OrderPanelBG.add(OrderImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 250, -1));

        OrderPanel.setBackground(new java.awt.Color(238, 238, 238));

        FoodPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FoodPrice.setText("PHP 100.00");

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        QuantityLabel.setText("Quantity");

        FoodName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FoodName.setText("Food Name");

        FoodDescription.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        FoodDescription.setText("Food Description");

        MinusButton.setText("-");
        MinusButton.setPreferredSize(new java.awt.Dimension(40, 30));
        MinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonActionPerformed(evt);
            }
        });

        plusButton.setText("+");
        plusButton.setPreferredSize(new java.awt.Dimension(40, 30));
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        Quantity.setBackground(new java.awt.Color(255, 255, 255));
        Quantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quantity.setText("1");
        Quantity.setOpaque(true);

        CartButton.setText("Add To Cart");
        CartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuantityLabel)
                    .addComponent(FoodDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(FoodName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuantityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        OrderPanelBG.add(OrderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        int currentQuantity = getQuantity();
        if (currentQuantity < 99) {
            // Increase quantity
            Quantity.setText(String.valueOf(currentQuantity + 1));
        }
    }//GEN-LAST:event_plusButtonActionPerformed

    private void MinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonActionPerformed
        int currentQuantity = getQuantity();
        if (currentQuantity > 1) {
            // Decrease quantity
            Quantity.setText(String.valueOf(currentQuantity - 1));
        }
    }//GEN-LAST:event_MinusButtonActionPerformed

    private void CartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartButtonActionPerformed
        CartButton.setText("Added to Cart");
        CartButton.setEnabled(false);
    }//GEN-LAST:event_CartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.app.assets.ColoredButton CartButton;
    private javax.swing.JLabel FoodDescription;
    private javax.swing.JLabel FoodName;
    private javax.swing.JLabel FoodPrice;
    private com.app.assets.ColoredButton MinusButton;
    private javax.swing.JLabel OrderImage;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JPanel OrderPanelBG;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel QuantityLabel;
    private com.app.assets.ColoredButton plusButton;
    // End of variables declaration//GEN-END:variables
}
