/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.assets;

/**
 *
 * @author Kirin
 */
public class ProductDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductDetailsPanel
     */
    public ProductDetailsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DetailsBG = new javax.swing.JPanel();
        ImageBG = new javax.swing.JPanel();
        FoodImage = new javax.swing.JLabel();
        FoodPrice = new javax.swing.JLabel();
        FoodName = new javax.swing.JLabel();
        RemoveButton = new com.app.assets.TextButton();
        Quantity = new javax.swing.JLabel();
        MinusButton = new com.app.assets.TextButton();
        PlusButton = new com.app.assets.TextButton();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 320));

        DetailsBG.setBackground(new java.awt.Color(241, 242, 237));
        DetailsBG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DetailsBG.setPreferredSize(new java.awt.Dimension(1240, 320));

        ImageBG.setBackground(new java.awt.Color(232, 205, 90));
        ImageBG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ImageBG.setPreferredSize(new java.awt.Dimension(250, 250));

        FoodImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FoodImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/images/foodimage.png"))); // NOI18N

        javax.swing.GroupLayout ImageBGLayout = new javax.swing.GroupLayout(ImageBG);
        ImageBG.setLayout(ImageBGLayout);
        ImageBGLayout.setHorizontalGroup(
            ImageBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImageBGLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(FoodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        ImageBGLayout.setVerticalGroup(
            ImageBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImageBGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FoodImage)
                .addGap(115, 115, 115))
        );

        FoodPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FoodPrice.setText("100.00");

        FoodName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FoodName.setText("Food Name");

        RemoveButton.setText("REMOVE");
        RemoveButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RemoveButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RemoveButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        Quantity.setBackground(new java.awt.Color(214, 211, 199));
        Quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Quantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quantity.setText("1");
        Quantity.setOpaque(true);

        MinusButton.setText("-");
        MinusButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonActionPerformed(evt);
            }
        });

        PlusButton.setText("+");
        PlusButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("0.00");

        javax.swing.GroupLayout DetailsBGLayout = new javax.swing.GroupLayout(DetailsBG);
        DetailsBG.setLayout(DetailsBGLayout);
        DetailsBGLayout.setHorizontalGroup(
            DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsBGLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(ImageBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsBGLayout.createSequentialGroup()
                        .addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(614, Short.MAX_VALUE))
                    .addGroup(DetailsBGLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FoodName, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(FoodPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        DetailsBGLayout.setVerticalGroup(
            DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsBGLayout.createSequentialGroup()
                .addGroup(DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsBGLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(FoodName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FoodPrice)
                            .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DetailsBGLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ImageBG, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DetailsBG, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DetailsBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonActionPerformed
        int currentQuantity = Integer.parseInt(Quantity.getText());
        if (currentQuantity > 1) {
            // Decrease quantity
            Quantity.setText(String.valueOf(currentQuantity - 1));
        }
    }//GEN-LAST:event_MinusButtonActionPerformed

    private void PlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusButtonActionPerformed
        int currentQuantity = Integer.parseInt(Quantity.getText());
        if (currentQuantity < 99) {
            // Increase quantity
            Quantity.setText(String.valueOf(currentQuantity + 1));
        }
    }//GEN-LAST:event_PlusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailsBG;
    private javax.swing.JLabel FoodImage;
    private javax.swing.JLabel FoodName;
    private javax.swing.JLabel FoodPrice;
    private javax.swing.JPanel ImageBG;
    private com.app.assets.TextButton MinusButton;
    private com.app.assets.TextButton PlusButton;
    private javax.swing.JLabel Quantity;
    private com.app.assets.TextButton RemoveButton;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
