/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.assets;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Kirin
 */
public class ProductDetailsPanel extends javax.swing.JPanel {

    private String foodName;
    private String foodDescription;
    private double foodPrice;
    private int foodQuantity;
    private double foodTotal;
    private int currentTotal;
    private QuantityChangeListener quantityChangeListener;
    
    
    public ProductDetailsPanel(String name, double price, int quantity) {
        // Call the existing constructor
        initComponents();
        setOpaque(false);

        // Set the name of the panel
        setName(name);

        this.foodName = name;
        this.foodPrice = price;
        this.foodQuantity = quantity;

        // Set the values in your labels or components here
        FoodName.setText(foodName);
        FoodPrice.setText(String.valueOf(foodPrice));
        Quantity.setText(String.valueOf(foodQuantity));

        // Debugging print statements
        System.out.println("Creating CartOrderPanel for: " + foodName);

        // Update the total label after setting initial values
        updateTotalLabel();
    }

    // Existing code...

    public void setOrderImage(ImageIcon imageIcon) {
        // Set the image for the PictureBox
        Image scaledImage = imageIcon.getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT);
        FoodImage.setIcon(new ImageIcon(scaledImage));

        // Update the total label when setting the image
        updateTotalLabel();
    }
   
   public int getQuantity() {
        return Integer.parseInt(Quantity.getText());
    }
   
    private void updateTotalLabel() {
        double total = calculateTotal();
        FoodTotal.setText(String.format("%.2f", total));
        revalidate();
        repaint();
    }
   
        public double calculateTotal() {
         return foodPrice * foodQuantity;
     }
        
    public interface QuantityChangeListener {
    void onQuantityChanged(String itemName, int newQuantity);
}
        
    public void setQuantityChangeListener(QuantityChangeListener listener) {
        this.quantityChangeListener = listener;
    }
    
    
        
    public void updateQuantity(int newQuantity) {
    this.foodQuantity = newQuantity;
    Quantity.setText(String.valueOf(foodQuantity));
    updateTotalLabel();

    if (quantityChangeListener != null) {
        quantityChangeListener.onQuantityChanged(foodName, newQuantity);
    }
}
    
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DetailsBG = new javax.swing.JPanel();
        ImageBG = new javax.swing.JPanel();
        FoodImage = new javax.swing.JLabel();
        FoodPrice = new javax.swing.JLabel();
        FoodName = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        FoodTotal = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 237));

        DetailsBG.setBackground(new java.awt.Color(241, 242, 237));
        DetailsBG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DetailsBG.setPreferredSize(new java.awt.Dimension(1100, 237));

        ImageBG.setBackground(new java.awt.Color(232, 205, 90));
        ImageBG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ImageBG.setPreferredSize(new java.awt.Dimension(200, 200));

        FoodImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FoodImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/images/foodimage.png"))); // NOI18N
        FoodImage.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout ImageBGLayout = new javax.swing.GroupLayout(ImageBG);
        ImageBG.setLayout(ImageBGLayout);
        ImageBGLayout.setHorizontalGroup(
            ImageBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ImageBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ImageBGLayout.createSequentialGroup()
                    .addComponent(FoodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ImageBGLayout.setVerticalGroup(
            ImageBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ImageBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ImageBGLayout.createSequentialGroup()
                    .addComponent(FoodImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        FoodPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FoodPrice.setText("100.00");

        FoodName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FoodName.setText("Food Name");

        Quantity.setBackground(new java.awt.Color(214, 211, 199));
        Quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Quantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quantity.setText("1");
        Quantity.setOpaque(true);

        FoodTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FoodTotal.setText("0.00");

        javax.swing.GroupLayout DetailsBGLayout = new javax.swing.GroupLayout(DetailsBG);
        DetailsBG.setLayout(DetailsBGLayout);
        DetailsBGLayout.setHorizontalGroup(
            DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsBGLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(ImageBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(FoodTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        DetailsBGLayout.setVerticalGroup(
            DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsBGLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsBGLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(DetailsBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FoodTotal)))
                    .addGroup(DetailsBGLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FoodName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FoodPrice))
                    .addComponent(ImageBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DetailsBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DetailsBG, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusButtonActionPerformed
    int currentQuantity = Integer.parseInt(Quantity.getText());
        if (currentQuantity < 99) {
            // Increase quantity
            foodQuantity = currentQuantity + 1;
            Quantity.setText(String.valueOf(foodQuantity));
            updateTotalLabel();
        }
    }//GEN-LAST:event_PlusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailsBG;
    private javax.swing.JLabel FoodImage;
    private javax.swing.JLabel FoodName;
    private javax.swing.JLabel FoodPrice;
    private javax.swing.JLabel FoodTotal;
    private javax.swing.JPanel ImageBG;
    private javax.swing.JLabel Quantity;
    // End of variables declaration//GEN-END:variables
}
