/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.transaction;

import com.app.details.FoodItem;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.JPanel;
import com.app.assets.CartOrderPanel;
import javax.swing.SwingUtilities;
import javax.swing.JLabel;
import javax.swing.BoxLayout;



/**
 * CartSection to display items in the shopping cart.
 * 
 * @author Kirin
 */
public class CartSection extends javax.swing.JPanel {

    public CartSection() {
        initComponents();  // Ensure that this method is called to initialize the components
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));  // Initialize cartPanel
        
    }


    public void displayCartItems(List<FoodItem> cartItems) {
        // Update the logic to display all items in cartItems
        removeAll(); // Clear the existing items in CartSection
        System.out.println("Items in the Cart:");

        for (FoodItem item : cartItems) {
            if (item.getUserQuantity() >= 1) {
                // Debugging print statements
                System.out.println("Name: " + item.getName());
                System.out.println("Quantity: " + item.getUserQuantity());
                System.out.println("Price: " + item.getPrice());
                System.out.println("Description: " + item.getDescription());
                System.out.println("Order ID: " + item.getOrderId());
                System.out.println("---------------------");

                // Create a JLabel with information and add it directly to CartSection
                String labelText = "<html>Name: " + item.getName() + "<br>Quantity: " + item.getUserQuantity() +
                                   "<br>Price: " + item.getPrice() + "<br>Description: " + item.getDescription() +
                                   "<br>Order ID: " + item.getOrderId() + "</html>";

                JLabel label = new JLabel(labelText);
                add(label);
            }
        }

        // Refresh CartSection on the EDT
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                revalidate();
                repaint();
            }
        });

        // Debugging print statement
        System.out.println("Displaying CartItems completed.");
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(1600, 900));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
