/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.transaction;

import com.app.details.FoodItem;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.JPanel;
import com.app.assets.CartOrderPanel;
import com.app.assets.ProductDetailsPanel;
import javax.swing.Box;
import javax.swing.SwingUtilities;
import javax.swing.JLabel;
import javax.swing.BoxLayout;



/**
 * CartSection to display items in the shopping cart.
 * 
 * @author Kirin
 */
public class CartSection extends javax.swing.JPanel {

    
    public CartSection() {
        initComponents();  // Ensure that this method is called to initialize the components // Initialize cartPanel
    }


    public void displayCartItems(List<FoodItem> cartItems) {
    // Clear the existing items in the JScrollPane

    JPanel cartOrderPanelContainer = new JPanel();
    cartOrderPanelContainer.setLayout(new BoxLayout(cartOrderPanelContainer, BoxLayout.Y_AXIS));

    for (FoodItem item : cartItems) {
        if (item.getUserQuantity() >= 1) {
        // Create a CartOrderPanel with information and add it to the container
            ProductDetailsPanel cartOrderPanel = new ProductDetailsPanel(
                    item.getName(),
                    item.getPrice(),
                    item.getUserQuantity()
            );
            cartOrderPanelContainer.setBackground(new java.awt.Color(241, 242, 237));
            cartOrderPanel.setOrderImage(item.getImageIcon());
            cartOrderPanelContainer.add(cartOrderPanel);
        }
    }

    // Add vertical glue to push CartOrderPanel instances to the top
    cartOrderPanelContainer.add(Box.createVerticalGlue());

    // Add the container to the existing JScrollPane
    OrderScrollPane.setViewportView(cartOrderPanelContainer);
    OrderScrollPane.setAlignmentX(LEFT_ALIGNMENT);  // Ensure the alignment is set to the left

    revalidate();
    repaint();

    // Debugging print statement
    System.out.println("Displaying CartItems completed.");
}







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderScrollPane = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(241, 242, 237));
        setPreferredSize(new java.awt.Dimension(1600, 900));

        OrderScrollPane.setBackground(new java.awt.Color(241, 242, 237));
        OrderScrollPane.setBorder(null);
        OrderScrollPane.setHorizontalScrollBar(null);
        OrderScrollPane.setPreferredSize(new java.awt.Dimension(1100, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(OrderScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(OrderScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane OrderScrollPane;
    // End of variables declaration//GEN-END:variables
}
